name: handlebars2
description: A dart wrapper around handlebars.js
version: 0.0.2
author: David Zhao <david.zhao@resentek.com>
homepage: https://github.com/zyzbroker/HandlebarDart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  rst_bootstrap: ^4.3.1


dev_dependencies:
  build_runner: ^1.3.1
  build_web_compilers: ^1.2.0
  sass_builder: ^2.1.2